### ISSUE TITLE
[의성마늘먹고 사람된 곰] 해커톤 앱 제출

### ISSUE THREAD

**Issue by Isoye12** [hackersground-kr/hackers-ground#1094]
### 제목

팀 앱 제출 2차

### 팀 이름

의성마늘먹고 사람된 곰

### 팀 리포지토리

https://github.com/hackersground-kr/hg-garlicBear

**Comment by bbukkubbang** [comment]
사전 준비 사항에 1, 2, 3 각각 까는 방법도 같이 올려주세요
