### ISSUE TITLE
[의성마늘먹고 사람된 곰] 해커톤 팀 발표자료 제출

### ISSUE THREAD

**Issue by Isoye12** [hackersground-kr/hackers-ground#1123]
### 제목

팀 발표자료 제출

### 팀 이름

의성마늘먹고 사람된 곰

### 팀 리포지토리

https://github.com/hackersground-kr/hg-garlicBear

**Comment by gye0n1** [comment]
<img width="1050" alt="스크린샷 2024-08-27 오후 12 01 04" src="https://github.com/user-attachments/assets/39a85b38-fe78-4d85-876b-79806f07adba">
