### ISSUE TITLE
[마늘장아찌] 해커톤 앱 제출

### ISSUE THREAD

**Issue by cher1shRXD** [hackersground-kr/hackers-ground#1137]
### 제목

팀 앱 제출 2차

### 팀 이름

마늘장아찌

### 팀 리포지토리

https://github.com/hackersground-kr/hg-team-garlic

**Comment by joshmoon827** [comment]
![image](https://github.com/user-attachments/assets/81d21bc2-3e99-4880-9f97-205bd2988517)
clone 및 후반 전체 과정이 구체적으로 되어 있지 않습니다
