### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by MJEvision** [hackersground-kr/hackers-ground#753]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/moonjongeun

### GitHub 리포지토리 URL

https://github.com/moonjongeun/aspire-app-dev-in-a-day-ko

### 프론트엔드 앱 URL

https://webapp.lemoncoast-b2647f37.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp.internal.lemoncoast-b2647f37.koreacentral.azurecontainerapps.io/

### 대시보드 앱 URL

https://aspire-dashboard.ext.lemoncoast-b2647f37.koreacentral.azurecontainerapps.io/

**Comment by zihyeon08** [comment]
@moonjongeun 
프론트 앱의 요구조건을 충족하지 않으셨습니다.
백엔드 앱의 weatherforcast 호출 시 데이터가 정상적으로 출력되지 않습니다.

**Comment by zihyeon08** [comment]
해당 문제를 해결하신 후, 다시 이슈를 생성해주세요.
