### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by 2P127** [hackersground-kr/hackers-ground#772]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/Haryu5412Dev

### GitHub 리포지토리 URL

https://github.com/Haryu5412Dev/.NET-Aspire-APP/tree/main

### 프론트엔드 앱 URL

https://webapp.blueforest-da5ab3f1.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp.blueforest-da5ab3f1.koreacentral.azurecontainerapps.io/

### 대시보드 앱 URL

https://aspire-dashboard.ext.blueforest-da5ab3f1.koreacentral.azurecontainerapps.io/

**Comment by clcok** [comment]
@Haryu5412Dev
프론트엔드 요구사항 확인 부탁드리고 이 이슈는 닫히니 다시 생성해주세요!
