### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by GayeongKimm** [hackersground-kr/hackers-ground#776]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/GayeongKimm

### GitHub 리포지토리 URL

https://github.com/GayeongKimm/2024-hackersgorund-workshop

### 프론트엔드 앱 URL

https://webapp--qwib2ek.calmsky-2515a7fb.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp--zfavvcr.calmsky-2515a7fb.koreacentral.azurecontainerapps.io/

### 대시보드 앱 URL

https://aspire-dashboard.ext.calmsky-2515a7fb.koreacentral.azurecontainerapps.io/

**Comment by clcok** [comment]
@GayeongKimm
API 서버에 접근이 불가능합니다!
수정해주시고 이 이슈는 닫히니 다시 생성해주세요!
