### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by TIMrsaa** [hackersground-kr/hackers-ground#782]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/PPqtae

### GitHub 리포지토리 URL

https://github.com/PPqtae/aspire-app-dev-in-a-day-ko

### 프론트엔드 앱 URL

https://webapp.victorioushill-eb7d68e5.koreacentral.azurecontainerapps.io

### 백엔드 앱 URL

https://apiapp.victorioushill-eb7d68e5.koreacentral.azurecontainerapps.io

### 대시보드 앱 URL

https://aspire-dashboard.ext.victorioushill-eb7d68e5.koreacentral.azurecontainerapps.io/

**Comment by clcok** [comment]
@PPqtae
프론트엔드 요구사항 확인 부탁드리고 이 이슈는 닫히니 다시 생성해주세요!

**Comment by TIMrsaa** [comment]
틀린 거 없을건데 한번 다시 검토 부탁드려도 될까요?

**Comment by zihyeon08** [comment]
과제 요구 사항과 프론트앱을 자세히 비교해주세요
