### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by kozae00** [hackersground-kr/hackers-ground#784]
### 제목

사전 워크샵

### GitHub 프로필 URL
https://github.com/kozae00

### 프론트엔드 앱 URL
https://webapp.mangosea-3bc35989.koreacentral.azurecontainerapps.io

### 백엔드 앱 URL
https://apiapp.internal.mangosea-3bc35989.koreacentral.azurecontainerapps.io

### 대시보드 앱 URL
https://aspire-dashboard.ext.mangosea-3bc35989.koreacentral.azurecontainerapps.io/

**Comment by zihyeon08** [comment]
@kozae00 리포에서 OpenAI API키가 노출된 것을 확인했습니다. 이슈는 닫히며, 사전워크샵을 위해 할당된 리소스 그룹 및 사용자 계정은 삭제됩니다.

수정 후 이슈를 제출하셔도 과제는 미완주처리됩니다. 리포는 4일 0시까지 삭제 부탁드리며, 삭제되지 않을 시 추가 패널티 부과되니 참고 부탁드립니다.

**Comment by kozae00** [comment]
@zihyeon08 comment가 늦게 수신될 줄 알고 뒤늦게 리포를 삭제한 점과 API키 노출된 점 죄송합니다. 
그러면 이러한 상황이면 과제 미완주처리로 해커톤 참여가 불가능하게되는건지 여쭙고 싶습니다.

**Comment by zihyeon08** [comment]
@kozae00 안녕하세요. 4일 0시 이후로 삭제하신 것이 확인되셨기 때문에 본선 점수에서 추가 페널티가 있을 수 있습니다.
본선 진출은 가능하십니다😊
