### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by GayeongKimm** [hackersground-kr/hackers-ground#787]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/GayeongKimm

### GitHub 리포지토리 URL

https://github.com/GayeongKimm/2024-hackersgorund-workshop

### 프론트엔드 앱 URL

https://webapp--r6hk0dd.calmsky-2515a7fb.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp--etahk9l.calmsky-2515a7fb.koreacentral.azurecontainerapps.io/

### 대시보드 앱 URL

https://aspire-dashboard.ext.calmsky-2515a7fb.koreacentral.azurecontainerapps.io/

**Comment by joshmoon827** [comment]
@GayeongKimm 프론트 오류(WebApp) 입니다. 확인해주세요

**Comment by zihyeon08** [comment]
@GayeongKimm 리포에서 OpenAI API키가 노출된 것을 확인했습니다. 이슈는 닫히며, 사전워크샵을 위해 할당된 리소스 그룹 및 사용자 계정은 삭제됩니다.

수정 후 이슈를 제출하셔도 과제는 미완주처리됩니다. 리포는 4일 0시까지 삭제 부탁드리며, 삭제되지 않을 시 추가 패널티 부과되니 참고 부탁드립니다.
