### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by hoit1011** [hackersground-kr/hackers-ground#790]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/hoit1011

### GitHub 리포지토리 URL

https://github.com/hoit1011/aspire-app-dev-in-a-day-ko

### 프론트엔드 앱 URL

https://webapp.orangeglacier-71343648.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp.internal.orangeglacier-71343648.koreacentral.azurecontainerapps.io/

### 대시보드 앱 URL

https://aspire-dashboard.ext.orangeglacier-71343648.koreacentral.azurecontainerapps.io/

**Comment by yujinverse** [comment]
@hoit1011  프론트 id 설정 , 백엔드 엔드포인트 호출 관련 오류 있습니다!
과제 원문 확인하시고 수정부탁드려요 😊

**Comment by zihyeon08** [comment]
이슈는 닫히니 이슈 재생성 부탁드립니다
