### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by heunseoRyu** [hackersground-kr/hackers-ground#801]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/heunseoRyu

### GitHub 리포지토리 URL

https://github.com/heunseoRyu/aspire-app-dev-in-a-day-ko

### 프론트엔드 앱 URL

https://webapp.nicesand-ab01ebc2.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp--h64dcsd.nicesand-ab01ebc2.koreacentral.azurecontainerapps.io

### 대시보드 앱 URL

https://aspire-dashboard.ext.nicesand-ab01ebc2.koreacentral.azurecontainerapps.io

**Comment by yujinverse** [comment]
@heunseoRyu 백엔드 json파일 형태의 데이터가 안불러와집니다 ㅠㅠ 
이 깃이슈는 곧 사라지니 새로운 이슈를 생성해주세요! :blush:
