### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by rjsgud49** [hackersground-kr/hackers-ground#814]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/rjsgud49

### GitHub 리포지토리 URL

https://github.com/rjsgud49/aspire-app-dev-in-a-day-ko

### 프론트엔드 앱 URL

https://webapp--2087uk0.gentleocean-9ef554a0.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp.gentleocean-9ef554a0.koreacentral.azurecontainerapps.io/

### 대시보드 앱 URL

https://aspire-dashboard.ext.gentleocean-9ef554a0.koreacentral.azurecontainerapps.io/

**Comment by joshmoon827** [comment]
front 오류 입니다.

**Comment by zihyeon08** [comment]
@rjsgud49 이 이슈는 닫히니 다시 이슈를 생성해주세요
