### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by heunseoRyu** [hackersground-kr/hackers-ground#826]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/heunseoRyu

### GitHub 리포지토리 URL

https://github.com/heunseoRyu/aspire-app-dev-in-a-day-ko

### 프론트엔드 앱 URL

https://webapp--583oak5.nicesand-ab01ebc2.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp--7oahhgl.nicesand-ab01ebc2.koreacentral.azurecontainerapps.io/swagger/index.html

### 대시보드 앱 URL

https://aspire-dashboard.ext.nicesand-ab01ebc2.koreacentral.azurecontainerapps.io/

**Comment by gye0n1** [comment]
@heunseoRyu 
백엔드 url이 잘못되었으니 확인 부탁드립니다 🙇‍♀️
이 이슈는 닫힐 예정이니 새롭게 이슈를 생성해주세요!
