### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by tomaho1756** [hackersground-kr/hackers-ground#856]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/tomaho1756

### GitHub 리포지토리 URL

https://github.com/tomaho1756/aspire-app-dev-in-a-day-ko

### 프론트엔드 앱 URL

https://webapp--zt8npoh.whitebay-852ff44e.koreacentral.azurecontainerapps.io

### 백엔드 앱 URL

https://apiapp--lov23w3.whitebay-852ff44e.koreacentral.azurecontainerapps.io/

### 대시보드 앱 URL

https://aspire-dashboard.ext.whitebay-852ff44e.koreacentral.azurecontainerapps.io/

**Comment by zihyeon08** [comment]
@tomaho1756 확인 결과 참가자 분 리포지토리에서 OpenAI API key가 노출 됨을 확인했습니다. 현 시간 부로 사전워크샵 과제 수행을 위한 애저 배포는 금지되며, 이슈를 다시 생성 하시더라도,검증 대상에서 제외 됩니다.

리포는 9일 0시까지 삭제 바랍니다. 삭제되어있지 않을 시 추가 페널티 부여합니다.
