### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by tlsalsco41122** [hackersground-kr/hackers-ground#864]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/tlsalsco41122

### GitHub 리포지토리 URL

https://github.com/tlsalsco41122/aspire-app-dev-in-a-day-ko

### 프론트엔드 앱 URL

https://webapp.lemonwave-08659855.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp.lemonwave-08659855.koreacentral.azurecontainerapps.io/

### 대시보드 앱 URL

https://aspire-dashboard.ext.lemonwave-08659855.koreacentral.azurecontainerapps.io/

**Comment by gye0n1** [comment]
@tlsalsco41122 
프론트에 오류가 있으니 확인 부탁드립니다 🙇‍♀️
이 이슈는 닫힐 예정이니 새롭게 이슈 생성 부탁드립니다!
