### ISSUE TITLE
사전 워크샵 과제 완료 인증

### ISSUE THREAD

**Issue by ahapwhs0414** [hackersground-kr/hackers-ground#865]
### 제목

사전 워크샵

### GitHub 프로필 URL

https://github.com/ahapwhs0414

### GitHub 리포지토리 URL

https://github.com/ahapwhs0414/aspire-app-dev-in-a-day-ko

### 프론트엔드 앱 URL

https://webapp--rm18bif.delightfulflower-67b603f5.koreacentral.azurecontainerapps.io/

### 백엔드 앱 URL

https://apiapp--fhqdkwk.delightfulflower-67b603f5.koreacentral.azurecontainerapps.io/

### 대시보드 앱 URL

https://aspire-dashboard.ext.delightfulflower-67b603f5.koreacentral.azurecontainerapps.io/

**Comment by zihyeon08** [comment]
@ahapwhs0414 자동화 과제 요건을 충족하지 않으셨습니다.
이 이슈는 닫히니 과제 요건을 충족하신 후 다시 이슈를 생성해주세요.
