### ISSUE TITLE
[이번 해커톤 옷 잘 만들었네] 해커톤 주제 제출

### ISSUE THREAD

**Issue by ahapwhs0414** [hackersground-kr/hackers-ground#913]
### 제목

팀 주제 제출

### 팀 이름

이번 해커톤 옷 잘 만들었네

### 팀 리포지토리

https://github.com/ahapwhs0414/hg-good-tshirt

**Comment by g1nya2** [comment]
내용물이 없습니다. 
과제를 하셔서 다시 제출해주세요!
