### ISSUE TITLE
[**크레센도**] 해커톤 앱 제출

### ISSUE THREAD

**Issue by osoohynn** [hackersground-kr/hackers-ground#938]
### 제목

팀 앱 제출 1차

### 팀 이름

크레센도

### 팀 리포지토리

https://github.com/hackersground-kr/hg-crescendo-server

**Comment by g1nya2** [comment]
0-3-1. AZD CLI 부분 윈도우에서 동작시 
C:\Users\USER>winget install microsoft.azd
'winget'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

위와 같은 오류가 뜹니다. winget 설치과정을 추가해주세요.
