### ISSUE TITLE
[**이번 해커톤 옷 잘 만들었네**] 해커톤 앱 제출

### ISSUE THREAD

**Issue by ahapwhs0414** [hackersground-kr/hackers-ground#980]
### 제목

팀 앱 제출 1차

### 팀 이름

이번 해커톤 옷 잘 만들었네

### 팀 리포지토리

https://github.com/hackersground-kr/hg-good-tshirt

**Comment by YoonKeumJae** [comment]
<img width="1596" alt="Screenshot 2024-08-26 at 19 49 47" src="https://github.com/user-attachments/assets/a42af639-3395-413b-aed3-610071763956">
오류가 발생했습니다. 확인해주세요!
