### ISSUE TITLE
[의성마늘먹고 사람된 곰] 해커톤 앱 제출

### ISSUE THREAD

**Issue by Isoye12** [hackersground-kr/hackers-ground#987]
### 제목

팀 앱 제출 1차

### 팀 이름

의성마늘먹고 사람된 곰

### 팀 리포지토리

https://github.com/hackersground-kr/hg-garlicBear

**Comment by joshmoon827** [comment]
![image](https://github.com/user-attachments/assets/6b09ea8c-3750-4d59-8c17-0a3ad4220ced)
git 스크립트파일이 존재하지 않습니다.
비전공자도 할 수 있도록 구성해주세요
