### ISSUE TITLE
[씨다씨] 해커톤 앱 제출

### ISSUE THREAD

**Issue by kozae00** [hackersground-kr/hackers-ground#990]
### 제목

팀 앱 제출 1차

### 팀 이름

씨다씨

### 팀 리포지토리

https://github.com/hackersground-kr/hg-CDC-team

**Comment by zihyeon08** [comment]
![image](https://github.com/user-attachments/assets/c0b9fd55-d39d-482c-8a88-f84d57026fdc)
비전공자는 바로 포크 할 수 없습니다.

비전공자도 문서만 보고 할 수 있도록 문서를 작성해주세요.
